Metrics/BlockLength:
  Exclude:
    # Ignore long blocks in tests This could perhaps be changed in the future.
    - 'spec/**/*'

Metrics/MethodLength:
  # Bump up allowed method length from the default of 10 lines. I don't want
  # this to become a slippery slope, but I think there is good use for slightly
  # longer methods.
  Max: 15

Style/Documentation:
  Exclude:
    - 'lib/peribot/version.rb'

Style/MethodMissing:
  Exclude:
    # Allow the block hash builder not to fall back on 'super'.
    - 'lib/peribot/util/block_hash_builder.rb'

Style/SignalException:
  EnforcedStyle: only_raise

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'bin/**/*'
