Style/Documentation:
  Exclude:
    - 'lib/peribot/version.rb'

Style/MethodMissing:
  Exclude:
    # Allow the block hash builder not to fall back on 'super'
    - 'lib/peribot/util/block_hash_builder.rb'

Style/SignalException:
  EnforcedStyle: only_raise

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'bin/**/*'
